services:
  app:
    container_name: app-java
    build: .
    ports:
      - 8082:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=nickchapo
      - spring.datasource.password=nickchapo
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nickchapo
      - POSTGRES_PASSWORD=nickchapo
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - 12346:5432
    volumes:
      - ./data:/var/lib/postgresql/data/